export default function Home() {
  return (
    <main className="page-shell">
      <nav className="nav-bar" aria-label="Main navigation">
        <a className="brand" href="#top" aria-label="Rosa home"><span className="brand-mark">r</span><span>rosa</span></a>
        <div className="nav-links"><a href="#story">Our story</a><a href="#ritual">The ritual</a><a href="#notes">Journal</a></div>
        <a className="nav-cta" href="#ritual">Explore product <span aria-hidden="true">↗</span></a>
      </nav>
      <section className="hero" id="top">
        <div className="hero-copy">
          <p className="eyebrow"><span /> Botanical care, reimagined</p>
          <h1>Feel good<br /><em>in your skin.</em></h1>
          <p className="hero-description">A daily ritual made with thoughtful ingredients, quiet confidence, and a little more care than you expected.</p>
          <div className="hero-actions"><a className="primary-button" href="#ritual">Meet the collection <span aria-hidden="true">↗</span></a><a className="text-link" href="#story">Why Rosa <span aria-hidden="true">↓</span></a></div>
          <div className="hero-proof"><div className="avatars" aria-label="Loved by our community"><span>AM</span><span>JS</span><span>NK</span></div><p><strong>4.9 / 5</strong><br /><span>Loved by 2,000+ people</span></p></div>
        </div>
        <div className="hero-art" aria-label="Rosa botanical body oil product"><div className="sun-disc" /><div className="arch-lines" /><div className="plant plant-left"><i /><b /><span /></div><div className="plant plant-right"><i /><b /><span /></div><div className="bottle-shadow" /><div className="bottle"><div className="bottle-cap" /><div className="bottle-label"><small>ROSA</small><strong>BODY<br />OIL</strong><span>no. 01</span></div></div><span className="art-caption">Neroli + rosehip<br />body oil / 100 ml</span></div>
      </section>
      <section className="marquee" aria-label="Rosa values"><span>Slow beauty</span><b>✳</b><span>Made with intention</span><b>✳</b><span>Good for your everyday</span><b>✳</b><span>Slow beauty</span></section>
      <section className="story-section" id="story"><div><p className="eyebrow"><span /> A softer standard</p><h2>Small rituals.<br /><em>Real results.</em></h2></div><div className="story-copy"><p>Rosa is a return to the essentials. We create uncomplicated body care that makes space for the moments between everything else.</p><a className="circle-link" href="#ritual" aria-label="Read our story">↗</a></div></section>
      <section className="ritual-section" id="ritual"><div className="section-heading"><div><p className="eyebrow"><span /> The daily ritual</p><h2>Three minutes<br /><em>to come back.</em></h2></div><p>Clean formulas. Comforting textures.<br />A small pause that belongs entirely to you.</p></div><div className="ritual-grid"><article className="ritual-card card-one"><span className="card-number">01</span><div className="mini-orb orb-one" /><h3>Warm<br />the moment</h3><p>Take a breath. Let the day soften around you.</p></article><article className="ritual-card card-two"><span className="card-number">02</span><div className="mini-orb orb-two" /><h3>Apply<br />generously</h3><p>Our silk-light oil sinks in without a trace.</p></article><article className="ritual-card card-three"><span className="card-number">03</span><div className="mini-orb orb-three" /><h3>Let it<br />linger</h3><p>Stay with the feeling. You have nowhere else to be.</p></article></div></section>
      <section className="quote-section" id="notes"><p className="quote-mark">“</p><blockquote>Rosa turns an everyday routine into the best part of my day.</blockquote><p className="quote-author">— Maya, Rosa community</p></section>
      <footer><a className="brand" href="#top"><span className="brand-mark">r</span><span>rosa</span></a><p>© 2024 Rosa Studio. Made for slow mornings.</p><a className="footer-link" href="mailto:hello@rosa.studio">hello@rosa.studio ↗</a></footer>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&family=Playfair+Display:ital,wght@0,500;0,600;1,500;1,600&display=swap');
        :root { --ink:#271c1c; --rose:#d5425a; --cream:#faf7f3; --line:#e8dfda; } *{box-sizing:border-box} html{scroll-behavior:smooth} body{margin:0;background:var(--cream);color:var(--ink);font-family:'Manrope',sans-serif} a{color:inherit;text-decoration:none}.page-shell{overflow:hidden}.nav-bar,.hero,.story-section,.ritual-section,footer{max-width:1240px;margin:0 auto;padding-left:42px;padding-right:42px}.nav-bar{height:96px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:10px;font-size:18px;font-weight:800;letter-spacing:-.05em}.brand-mark{display:grid;place-items:center;width:28px;height:28px;color:white;background:var(--rose);border-radius:50% 50% 50% 4px;font-family:Georgia,serif;font-size:21px;font-weight:400;font-style:italic}.nav-links{display:flex;gap:35px;margin-left:110px;font-size:12px;font-weight:600;color:#746766}.nav-links a,.text-link,.footer-link{transition:color .2s ease}.nav-links a:hover,.text-link:hover,.footer-link:hover{color:var(--rose)}.nav-cta{border-bottom:1px solid var(--ink);padding:6px 0;font-size:12px;font-weight:700}.nav-cta span,.primary-button span{margin-left:12px;font-size:15px}
        .hero{min-height:690px;display:grid;grid-template-columns:46% 54%;align-items:center;padding-top:48px;padding-bottom:70px}.eyebrow{display:flex;align-items:center;gap:10px;margin:0 0 28px;color:var(--rose);font-family:'DM Mono',monospace;font-size:10px;letter-spacing:.1em;text-transform:uppercase}.eyebrow span{width:24px;height:1px;background:currentColor}h1,h2,h3,p{margin-top:0}h1{margin-bottom:27px;font-size:clamp(56px,6.5vw,90px);line-height:.96;letter-spacing:-.075em;font-weight:700}h1 em,h2 em{color:var(--rose);font-family:'Playfair Display',Georgia,serif;font-weight:500;letter-spacing:-.07em}.hero-description{max-width:350px;color:#776968;font-size:14px;line-height:1.8}.hero-actions{display:flex;align-items:center;gap:27px;margin-top:36px}.primary-button{display:inline-flex;align-items:center;padding:15px 20px;color:white;background:var(--rose);font-size:11px;font-weight:700;transition:transform .2s ease,background .2s ease}.primary-button:hover{background:#b92f47;transform:translateY(-2px)}.text-link{border-bottom:1px solid #bdabaa;padding-bottom:5px;color:#6d5e5c;font-size:11px;font-weight:700}.text-link span{margin-left:9px;color:var(--rose)}.hero-proof{display:flex;align-items:center;gap:15px;margin-top:67px}.avatars{display:flex;padding-left:7px}.avatars span{display:grid;place-items:center;width:28px;height:28px;margin-left:-7px;border:2px solid var(--cream);border-radius:50%;color:white;background:#bd8481;font-size:7px;font-weight:700}.avatars span:nth-child(2){background:#9b6968}.avatars span:nth-child(3){background:#e3a18e}.hero-proof p{margin:0;color:#796a68;font-size:10px;line-height:1.5}.hero-proof strong{color:var(--ink);font-size:11px}
        .hero-art{position:relative;height:575px;margin-left:20px;background:#f2d7d2;overflow:hidden}.sun-disc{position:absolute;width:430px;height:430px;top:43px;left:calc(50% - 215px);border-radius:50%;background:#e98a89}.arch-lines{position:absolute;width:350px;height:395px;left:calc(50% - 175px);top:92px;border:1px solid rgba(255,255,255,.55);border-bottom:0;border-radius:220px 220px 0 0}.bottle{position:absolute;z-index:2;width:147px;height:279px;bottom:99px;left:calc(50% - 73px);border-radius:20px 20px 17px 17px;background:linear-gradient(90deg,#bb333b,#e35356 45%,#b82f39);box-shadow:24px 34px 32px rgba(117,45,38,.2);transform:rotate(4deg)}.bottle::after{content:'';position:absolute;right:14px;top:0;width:24px;height:100%;border-radius:0 18px 15px 0;background:rgba(255,255,255,.08)}.bottle-cap{position:absolute;width:68px;height:52px;top:-44px;left:39px;border-radius:8px 8px 3px 3px;background:#7c4946;box-shadow:inset 7px 0 rgba(255,255,255,.08)}.bottle-label{position:absolute;z-index:1;top:76px;left:17px;width:113px;height:135px;display:flex;flex-direction:column;align-items:center;justify-content:center;background:#f7e4d4;color:#6f3c36;transform:rotate(-2deg)}.bottle-label small,.bottle-label span{font-family:'DM Mono',monospace;font-size:8px;letter-spacing:.18em}.bottle-label strong{margin:12px 0;font-family:Georgia,serif;font-size:20px;line-height:.86;text-align:center;letter-spacing:.04em}.bottle-label span{font-size:6px;letter-spacing:.12em}.bottle-shadow{position:absolute;z-index:1;width:245px;height:27px;bottom:75px;left:calc(50% - 112px);border-radius:50%;background:rgba(106,48,44,.17);filter:blur(7px)}.plant{position:absolute;z-index:3;bottom:-12px;width:130px;height:330px}.plant-left{left:13px;transform:rotate(-17deg)}.plant-right{right:14px;transform:rotate(18deg) scaleX(-1)}.plant i,.plant b,.plant span{position:absolute;bottom:0;display:block;width:8px;height:280px;border-radius:100% 0;background:#665542;transform:rotate(14deg)}.plant b{left:28px;height:200px;transform:rotate(-13deg)}.plant span{left:60px;height:245px;transform:rotate(18deg)}.plant::after,.plant::before{content:'';position:absolute;width:54px;height:22px;border-radius:100% 0 100% 0;background:#52684b}.plant::after{left:0;top:102px;transform:rotate(23deg)}.plant::before{left:45px;top:170px;transform:rotate(-23deg)}.art-caption{position:absolute;z-index:4;right:22px;bottom:20px;color:#805752;font-family:'DM Mono',monospace;font-size:8px;line-height:1.5;text-align:right;text-transform:uppercase}
        .marquee{display:flex;justify-content:center;align-items:center;gap:34px;padding:18px 24px;color:white;background:var(--rose);font-family:'DM Mono',monospace;font-size:10px;letter-spacing:.08em;text-transform:uppercase}.marquee b{font-size:14px;font-weight:400}.story-section{display:grid;grid-template-columns:1fr 1fr;gap:80px;padding-top:135px;padding-bottom:145px}.story-section h2,.ritual-section h2{margin:0;font-size:clamp(43px,5vw,67px);line-height:.98;letter-spacing:-.075em}.story-copy{max-width:370px;align-self:end;color:#796b68;font-size:14px;line-height:1.9}.circle-link{display:grid;place-items:center;width:42px;height:42px;margin-top:31px;border:1px solid var(--rose);border-radius:50%;color:var(--rose);transition:color .2s,background .2s}.circle-link:hover{color:white;background:var(--rose)}.ritual-section{padding-bottom:140px}.section-heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:47px}.section-heading .eyebrow{margin-bottom:21px}.section-heading>p{margin:0 0 4px;color:#796b68;font-size:12px;line-height:1.7;text-align:right}.ritual-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:17px}.ritual-card{position:relative;min-height:326px;padding:26px;overflow:hidden}.card-one{background:#f0ded3}.card-two{background:#ead1d5}.card-three{background:#edcfbd}.card-number{position:relative;z-index:2;color:var(--rose);font-family:'DM Mono',monospace;font-size:10px}.ritual-card h3{position:relative;z-index:2;margin:128px 0 12px;color:#553c3a;font-family:'Playfair Display',Georgia,serif;font-size:29px;line-height:.92;font-weight:500}.ritual-card p{position:relative;z-index:2;max-width:165px;margin:0;color:#7c6862;font-size:10px;line-height:1.6}.mini-orb{position:absolute;width:175px;height:175px;top:30px;right:30px;border-radius:50%}.orb-one{background:#e8ae98}.orb-two{background:#d58893}.orb-three{background:#dfa077}.mini-orb::after{content:'';position:absolute;width:48px;height:48px;left:58px;top:58px;border:1px solid rgba(255,255,255,.65);border-radius:50%}
        .quote-section{display:flex;flex-direction:column;align-items:center;padding:105px 24px 112px;color:white;background:#2f2020;text-align:center}.quote-mark{height:36px;margin:0 0 18px;color:#ed8b8a;font-family:Georgia,serif;font-size:65px;line-height:1}.quote-section blockquote{max-width:660px;margin:0;font-family:'Playfair Display',Georgia,serif;font-size:clamp(27px,4vw,45px);line-height:1.15;letter-spacing:-.04em}.quote-author{margin:27px 0 0;color:#baaaa6;font-family:'DM Mono',monospace;font-size:9px;letter-spacing:.08em;text-transform:uppercase}footer{display:flex;align-items:center;justify-content:space-between;min-height:110px}footer p,footer .footer-link{margin:0;color:#887875;font-size:10px}footer .footer-link{color:var(--rose);font-family:'DM Mono',monospace}
        @media(max-width:760px){.nav-bar,.hero,.story-section,.ritual-section,footer{padding-left:22px;padding-right:22px}.nav-bar{height:78px}.nav-links{display:none}.nav-cta{font-size:10px}.hero{display:flex;flex-direction:column;align-items:stretch;padding-top:72px}.hero-copy{padding-bottom:65px}.hero-art{width:100%;height:450px;margin-left:0}.sun-disc{width:320px;height:320px;left:calc(50% - 160px)}.arch-lines{width:270px;height:320px;left:calc(50% - 135px);top:61px}.bottle{bottom:79px;transform:scale(.82) rotate(4deg)}.bottle-shadow{bottom:62px}.plant{transform:scale(.78) rotate(-17deg);transform-origin:bottom left}.plant-right{transform:scaleX(-1) scale(.78) rotate(18deg);transform-origin:bottom right}.marquee{justify-content:flex-start;overflow:hidden;white-space:nowrap;gap:20px;font-size:8px}.marquee span:nth-of-type(2),.marquee span:nth-of-type(3),.marquee b:nth-of-type(2),.marquee b:nth-of-type(3){display:none}.story-section{display:block;padding-top:90px;padding-bottom:90px}.story-copy{margin-top:42px}.section-heading{display:block}.section-heading>p{margin-top:25px;text-align:left}.ritual-grid{grid-template-columns:1fr}.ritual-card{min-height:280px}.ritual-card h3{margin-top:105px}.quote-section{padding-top:80px;padding-bottom:85px}footer{flex-wrap:wrap;gap:16px;padding-top:28px;padding-bottom:28px}footer p{order:3;flex-basis:100%}}
  `}</style>
    </main>
  );
}
